package mib.grupp.pkg15;

import oru.inf.InfDB;



/**
 *
 * @author Linda
 */
public class AdminStartSkärm extends javax.swing.JFrame {
    private String användarnamn;
    /**
     * Creates new form AdminStartSkärm
     */
    public AdminStartSkärm() {
        initComponents();
    }
    
    /**
     * Creates new form AdminStartSkärm
     */
    public AdminStartSkärm(String användarnamn) {
        initComponents();
        this.användarnamn = användarnamn;
        lblRubrik.setText("Välkommen: " + användarnamn);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRubrik = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblRubrik.setText("Välkommen");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lblRubrik)
                .addContainerGap(315, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(lblRubrik)
                .addContainerGap(269, Short.MAX_VALUE))
        );

        lblRubrik.getAccessibleContext().setAccessibleName("lblVälkommen");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblRubrik;
    // End of variables declaration//GEN-END:variables
}
